version: '3.8'

services:
  # ğŸ˜ VeritabanÄ± Servisi (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: secure-wallet-db
    restart: always
    environment:
      POSTGRES_USER: walletuser      # KullanÄ±cÄ± adÄ±
      POSTGRES_PASSWORD: walletpassword # Åifre
      POSTGRES_DB: walletdb          # VeritabanÄ± AdÄ±
    ports:
      - "5433:5432" # DÄ°KKAT: BilgisayarÄ±mÄ±zÄ±n 5433 kapÄ±sÄ±nÄ±, Docker'Ä±n 5432 kapÄ±sÄ±na baÄŸlÄ±yoruz.
    volumes:
      - wallet_data:/var/lib/postgresql/data

  # ğŸ›ï¸ YÃ¶netim Paneli (Adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080" # DÄ°KKAT: TarayÄ±cÄ±dan http://localhost:8081 adresinden gireceÄŸiz.
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  wallet_data: